# Generated by Django 4.2.7 on 2025-09-15 15:24

import bookings.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venues', '0001_initial'),
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_code', models.CharField(default=bookings.models.generate_booking_code, max_length=20, unique=True, verbose_name='Mã đặt vé')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Tên khách hàng')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('customer_id_number', models.CharField(blank=True, max_length=20, verbose_name='CMND/CCCD')),
                ('status', models.CharField(choices=[('pending', 'Chờ thanh toán'), ('paid', 'Đã thanh toán'), ('cancelled', 'Đã hủy'), ('expired', 'Hết hạn'), ('refunded', 'Đã hoàn tiền')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tổng tiền')),
                ('service_fee', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Phí dịch vụ')),
                ('discount_amount', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Giảm giá')),
                ('final_amount', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Thành tiền')),
                ('session_id', models.CharField(blank=True, max_length=100, verbose_name='Session ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(verbose_name='Thời gian hết hạn')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian thanh toán')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='shows.performance', verbose_name='Suất diễn')),
            ],
            options={
                'verbose_name': 'Đơn đặt vé',
                'verbose_name_plural': 'Đơn đặt vé',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SeatReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'Trống'), ('reserved', 'Đang giữ'), ('sold', 'Đã bán'), ('blocked', 'Khóa')], default='available', max_length=20, verbose_name='Trạng thái')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Giá vé')),
                ('session_id', models.CharField(blank=True, max_length=100, verbose_name='Session ID')),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Hết hạn giữ chỗ')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seat_reservations', to='bookings.booking', verbose_name='Đơn đặt')),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_reservations', to='shows.performance', verbose_name='Suất diễn')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='venues.seat', verbose_name='Ghế')),
            ],
            options={
                'verbose_name': 'Ghế đặt',
                'verbose_name_plural': 'Ghế đặt',
                'unique_together': {('performance', 'seat')},
            },
        ),
    ]
