# Generated by Django 4.2 on 2025-10-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer_address',
            field=models.TextField(blank=True, verbose_name='Địa chỉ nhận vé'),
        ),
        migrations.AddField(
            model_name='booking',
            name='shipping_time',
            field=models.CharField(choices=[('business_hours', 'Trong giờ hành chính'), ('after_hours', 'Ngoài giờ hành chính')], default='business_hours', max_length=50, verbose_name='Thời gian ship'),
        ),
    ]
