# Generated by Django 4.2 on 2025-10-14 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0001_initial'),
        ('bookings', '0002_booking_customer_address_booking_shipping_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='discounts.discount'),
        ),
    ]
