# Generated by Django 4.2 on 2025-10-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_discount'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='seatreservation',
            index=models.Index(fields=['performance', 'seat', 'status'], name='bookings_se_perform_82d059_idx'),
        ),
        migrations.AddIndex(
            model_name='seatreservation',
            index=models.Index(fields=['session_id', 'status', 'expires_at'], name='bookings_se_session_04baf1_idx'),
        ),
        migrations.AddIndex(
            model_name='seatreservation',
            index=models.Index(fields=['booking', 'status'], name='bookings_se_booking_0c8275_idx'),
        ),
    ]
