# Generated by Django 4.2 on 2025-10-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_seatreservation_bookings_se_perform_82d059_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatreservation',
            name='client_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
