# Generated by Django 4.2 on 2025-10-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_seatreservation_client_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Phí vận chuyển'),
        ),
    ]
