# Generated by Django 4.2 on 2025-10-19 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_shipping_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_code', models.CharField(db_index=True, max_length=10)),
                ('action', models.CharField(choices=[('reserve_seat', 'Đặt giữ chỗ'), ('create_booking', 'Tạo booking'), ('payment_initiated', 'Bắt đầu thanh toán'), ('payment_success', 'Thanh toán thành công'), ('payment_failed', 'Thanh toán thất bại'), ('booking_expired', 'Booking hết hạn'), ('booking_cancelled', 'Hủy booking'), ('seat_released', 'Giải phóng ghế')], max_length=50)),
                ('seats_snapshot', models.JSONField(default=list, help_text='Danh sách ghế tại thời điểm action xảy ra')),
                ('session_id', models.CharField(blank=True, max_length=255)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('payment_status', models.CharField(blank=True, max_length=50)),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('stack_trace', models.TextField(blank=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Booking History',
                'verbose_name_plural': 'Booking Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='bookinghistory',
            index=models.Index(fields=['-created_at'], name='bookings_bo_created_f9dd45_idx'),
        ),
        migrations.AddIndex(
            model_name='bookinghistory',
            index=models.Index(fields=['booking_code', '-created_at'], name='bookings_bo_booking_377e15_idx'),
        ),
        migrations.AddIndex(
            model_name='bookinghistory',
            index=models.Index(fields=['session_id', '-created_at'], name='bookings_bo_session_d688d9_idx'),
        ),
    ]
