services:
    db:
        image: postgres:15-alpine
        container_name: booking_db_prod
        restart: always
        ports:
            - "5432:5432"
        volumes:
            - postgres_data_prod:/var/lib/postgresql/data
            - ./backups:/backups
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        networks:
            - booking_network_prod
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U admin"]
            interval: 10s
            timeout: 5s
            retries: 5

    redis:
        image: redis:7-alpine
        container_name: booking_redis_prod
        restart: always
        ports:
            - "6379:6379"
        command: redis-server --appendonly yes
        volumes:
            - redis_data_prod:/data
        networks:
            - booking_network_prod
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 10s
            timeout: 5s
            retries: 5

volumes:
    postgres_data_prod:
    redis_data_prod:

networks:
    booking_network_prod:
        external: true # ✅ ĐỔI THÀNH external: true
