# Generated by Django 4.2.7 on 2025-09-15 15:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên vở diễn')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('category', models.CharField(max_length=100, verbose_name='Thể loại')),
                ('duration_minutes', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Thời lượng (phút)')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='shows/posters/', verbose_name='Poster')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venues.venue', verbose_name='Nhà hát')),
            ],
            options={
                'verbose_name': 'Vở diễn',
                'verbose_name_plural': 'Vở diễn',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Ngày giờ diễn')),
                ('status', models.CharField(choices=[('scheduled', 'Đã lên lịch'), ('on_sale', 'Đang bán'), ('sold_out', 'Hết vé'), ('cancelled', 'Đã hủy'), ('completed', 'Đã diễn')], default='scheduled', max_length=20, verbose_name='Trạng thái')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='shows.show')),
            ],
            options={
                'verbose_name': 'Suất diễn',
                'verbose_name_plural': 'Suất diễn',
                'ordering': ['datetime'],
            },
        ),
        migrations.CreateModel(
            name='PerformancePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Giá')),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='shows.performance')),
                ('price_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venues.pricecategory')),
            ],
            options={
                'verbose_name': 'Giá suất diễn',
                'verbose_name_plural': 'Giá suất diễn',
                'unique_together': {('performance', 'price_category')},
            },
        ),
    ]
