# Generated by Django 4.2 on 2025-10-12 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('image', models.ImageField(help_text='Kích thước khuyến nghị: 1920x600px cho desktop, tự động resize cho mobile', upload_to='posters/', verbose_name='Ảnh poster')),
                ('order', models.IntegerField(default=0, help_text='Số nhỏ hơn sẽ hiển thị trước', verbose_name='Thứ tự hiển thị')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posters', to='shows.show', verbose_name='Vở diễn liên kết')),
            ],
            options={
                'verbose_name': 'Banner/Poster',
                'verbose_name_plural': 'Banner/Poster',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
