# Generated by Django 4.2 on 2025-10-12 17:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='service_fee_per_ticket',
            field=models.DecimalField(decimal_places=0, default=10000, help_text='Phí dịch vụ tính cho mỗi vé (VNĐ)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Phí dịch vụ mỗi vé'),
        ),
    ]
