# Generated by Django 4.2 on 2025-10-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0003_show_service_fee_per_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Phí vận chuyển'),
        ),
    ]
