# Generated by Django 4.2 on 2025-10-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0004_performance_shipping_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='description_markdown',
            field=models.TextField(blank=True, help_text='Mô tả chi tiết hỗ trợ Markdown, có thể chèn ảnh và video', verbose_name='Mô tả chi tiết (Markdown)'),
        ),
        migrations.AddField(
            model_name='show',
            name='trailer_url',
            field=models.URLField(blank=True, help_text='Link YouTube trailer (vd: https://www.youtube.com/watch?v=xxxxx)', null=True, verbose_name='Link YouTube Trailer'),
        ),
    ]
