# Generated by Django 4.2 on 2025-10-18 10:22

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0005_show_description_markdown_show_trailer_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='description_markdown',
            field=markdownx.models.MarkdownxField(blank=True, help_text='Sử dụng Markdown để định dạng văn bản. Hỗ trợ: **bold**, *italic*, [links](url), ![images](url), ### headings, etc.', verbose_name='Mô tả chi tiết (Markdown)'),
        ),
    ]
