# Generated by Django 5.2.7 on 2025-10-25 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0006_alter_show_description_markdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='max_tickets_per_booking',
            field=models.PositiveIntegerField(default=8, help_text='Số lượng vé tối đa khách hàng có thể đặt trong suất diễn này', verbose_name='Số vé tối đa mỗi đơn'),
        ),
    ]
