# Generated by Django 4.2 on 2025-10-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('vnpay', 'VNPay'), ('momo', 'MoMo'), ('bank', 'Chuyển khoản'), ('card', 'Thẻ quốc tế'), ('9pay', '9Pay')], max_length=20, verbose_name='Phương thức thanh toán'),
        ),
    ]
