services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins-cicd
    restart: unless-stopped
    privileged: true
    user: root
    ports:
      - "8080:8080"    # Jenkins Web UI
      - "50000:50000"  # Jenkins Agent
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose:ro
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - JENKINS_OPTS="--httpPort=8080"
      - JAVA_OPTS="-Dhudson.security.csrf.GlobalCrumbIssuerConfiguration.DISABLE_CSRF_PROTECTION=true"
    networks:
      - jenkins-net

networks:
  jenkins-net:
    driver: bridge

volumes:
  jenkins_home:
    driver: local
