# Generated by Django 4.2.7 on 2025-09-15 15:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên loại vé')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã')),
                ('base_price', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Giá cơ bản')),
                ('color', models.CharField(default='#CCCCCC', max_length=7, verbose_name='Màu hiển thị')),
            ],
            options={
                'verbose_name': 'Loại giá vé',
                'verbose_name_plural': 'Loại giá vé',
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên nhà hát')),
                ('address', models.TextField(verbose_name='Địa chỉ')),
                ('phone', models.CharField(max_length=20, verbose_name='Điện thoại')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Nhà hát',
                'verbose_name_plural': 'Nhà hát',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên khu vực')),
                ('code', models.CharField(max_length=20, verbose_name='Mã khu vực')),
                ('position_x', models.IntegerField(default=0, verbose_name='Vị trí X')),
                ('position_y', models.IntegerField(default=0, verbose_name='Vị trí Y')),
                ('order', models.IntegerField(default=0, verbose_name='Thứ tự')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='venues.venue')),
            ],
            options={
                'verbose_name': 'Khu vực',
                'verbose_name_plural': 'Khu vực',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=10, verbose_name='Nhãn hàng')),
                ('seat_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Số ghế')),
                ('position_y', models.IntegerField(default=0, verbose_name='Vị trí Y')),
                ('price_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='venues.pricecategory', verbose_name='Loại giá')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='venues.section')),
            ],
            options={
                'verbose_name': 'Hàng ghế',
                'verbose_name_plural': 'Hàng ghế',
                'ordering': ['position_y'],
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Số ghế')),
                ('position_x', models.IntegerField(default=0, verbose_name='Vị trí X')),
                ('position_y', models.IntegerField(default=0, verbose_name='Vị trí Y')),
                ('status', models.CharField(choices=[('active', 'Hoạt động'), ('maintenance', 'Bảo trì'), ('disabled', 'Vô hiệu hóa')], default='active', max_length=20, verbose_name='Trạng thái')),
                ('is_accessible', models.BooleanField(default=False, verbose_name='Ghế cho người khuyết tật')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='venues.row')),
            ],
            options={
                'verbose_name': 'Ghế',
                'verbose_name_plural': 'Ghế',
                'ordering': ['row', 'number'],
                'unique_together': {('row', 'number')},
            },
        ),
    ]
