# Generated by Django 4.2.7 on 2025-09-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Theater Booking', max_length=100, verbose_name='Tên tổ chức')),
                ('hotline', models.CharField(max_length=20, verbose_name='Hotline')),
                ('support_email', models.EmailField(max_length=254, verbose_name='Email hỗ trợ')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook URL')),
                ('tiktok_url', models.URLField(blank=True, verbose_name='TikTok URL')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram URL')),
                ('website_url', models.URLField(blank=True, verbose_name='Website URL')),
                ('logo_url', models.URLField(default='https://lh3.googleusercontent.com/pw/AP1GczOeY1ZKKsObbQ5Em5H14byD0GRz_-ydPBGZWzBOQbun4cB783CMb3NsYbucZAmrMlCE-YJ8r3Ll71Fthb-wyaMjuQbPTc1jAPLcf-3-NzjBqBuS_3NB2W6JzfAWZP3sRYBVzVxethfg4iJBam3EhoDp=w489-h301-s-no-gm', verbose_name='Logo URL')),
                ('copyright_text', models.CharField(default='GMCP by duongcamart', max_length=100, verbose_name='Copyright text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Thông tin liên hệ',
                'verbose_name_plural': 'Thông tin liên hệ',
            },
        ),
        migrations.AlterModelOptions(
            name='row',
            options={'ordering': ['label'], 'verbose_name': 'Hàng ghế', 'verbose_name_plural': 'Hàng ghế'},
        ),
        migrations.AlterModelOptions(
            name='venue',
            options={'ordering': ['name'], 'verbose_name': 'Nhà hát', 'verbose_name_plural': 'Nhà hát'},
        ),
        migrations.RemoveField(
            model_name='venue',
            name='description',
        ),
        migrations.AddField(
            model_name='row',
            name='name',
            field=models.CharField(blank=True, max_length=10, verbose_name='Tên hàng'),
        ),
        migrations.AddField(
            model_name='venue',
            name='capacity',
            field=models.IntegerField(default=0, verbose_name='Sức chứa'),
        ),
        migrations.AddField(
            model_name='venue',
            name='checkin_minutes_before',
            field=models.IntegerField(default=45, verbose_name='Check-in trước bao nhiêu phút'),
        ),
        migrations.AddField(
            model_name='venue',
            name='code',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Mã địa điểm'),
        ),
        migrations.AddField(
            model_name='venue',
            name='copyright_text',
            field=models.CharField(blank=True, max_length=100, verbose_name='Copyright text'),
        ),
        migrations.AddField(
            model_name='venue',
            name='facebook_url',
            field=models.URLField(blank=True, verbose_name='Facebook URL'),
        ),
        migrations.AddField(
            model_name='venue',
            name='hotline',
            field=models.CharField(blank=True, max_length=20, verbose_name='Hotline'),
        ),
        migrations.AddField(
            model_name='venue',
            name='instagram_url',
            field=models.URLField(blank=True, verbose_name='Instagram URL'),
        ),
        migrations.AddField(
            model_name='venue',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AddField(
            model_name='venue',
            name='layout_image',
            field=models.ImageField(blank=True, null=True, upload_to='venues/layouts/', verbose_name='Hình layout'),
        ),
        migrations.AddField(
            model_name='venue',
            name='logo_url',
            field=models.URLField(blank=True, verbose_name='Logo URL'),
        ),
        migrations.AddField(
            model_name='venue',
            name='support_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email hỗ trợ'),
        ),
        migrations.AddField(
            model_name='venue',
            name='tiktok_url',
            field=models.URLField(blank=True, verbose_name='TikTok URL'),
        ),
        migrations.AddField(
            model_name='venue',
            name='website_url',
            field=models.URLField(blank=True, verbose_name='Website URL'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='is_accessible',
            field=models.BooleanField(default=False, verbose_name='Ghế người khuyết tật'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='number',
            field=models.CharField(max_length=10, verbose_name='Số ghế'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='status',
            field=models.CharField(choices=[('active', 'Hoạt động'), ('broken', 'Hỏng'), ('maintenance', 'Bảo trì'), ('reserved', 'Để dành')], default='active', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Tên địa điểm'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Điện thoại'),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('venue', 'code')},
        ),
    ]
