# Generated by Django 4.2.7 on 2025-09-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_add_contact_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='description',
            field=models.TextField(blank=True, verbose_name='Mô tả'),
        ),
    ]
