# Generated by Django 4.2.7 on 2025-09-28 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0003_venue_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên layout')),
                ('venue_type', models.CharField(choices=[('opera', 'Nhà hát Opera'), ('concert', 'Phòng hòa nhạc'), ('theater', 'Rạp hát'), ('cinema', 'Rạp chiếu phim'), ('stadium', 'Sân vận động')], max_length=20, verbose_name='Loại nhà hát')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('config', models.JSONField(verbose_name='Cấu hình layout')),
                ('is_template', models.BooleanField(default=True, verbose_name='Là template')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Layout nhà hát',
                'verbose_name_plural': 'Layout nhà hát',
            },
        ),
        migrations.AddField(
            model_name='venue',
            name='venue_type',
            field=models.CharField(choices=[('opera', 'Nhà hát Opera'), ('concert', 'Phòng hòa nhạc'), ('theater', 'Rạp hát'), ('cinema', 'Rạp chiếu phim'), ('stadium', 'Sân vận động')], default='theater', max_length=20, verbose_name='Loại nhà hát'),
        ),
        migrations.AddField(
            model_name='venue',
            name='layout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='venues.venuelayout', verbose_name='Layout template'),
        ),
    ]
