# Generated by Django 4.2.7 on 2025-09-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0004_venuelayout_venue_venue_type_venue_layout'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='row',
            options={'ordering': ['position_y'], 'verbose_name': 'Hàng ghế', 'verbose_name_plural': 'Hàng ghế'},
        ),
        migrations.RemoveField(
            model_name='row',
            name='name',
        ),
        migrations.AddField(
            model_name='row',
            name='aisle_width',
            field=models.IntegerField(default=60, verbose_name='Độ rộng lối đi giữa'),
        ),
        migrations.AddField(
            model_name='row',
            name='center_x',
            field=models.IntegerField(default=400, verbose_name='Vị trí trung tâm X (cho center_out)'),
        ),
        migrations.AddField(
            model_name='row',
            name='gaps',
            field=models.JSONField(blank=True, default=list, help_text='Danh sách số ghế bị ẩn để tạo lối đi. VD: [8,9,26,27]', verbose_name='Vị trí ghế bị ẩn/lối đi'),
        ),
        migrations.AddField(
            model_name='row',
            name='has_center_aisle',
            field=models.BooleanField(default=True, verbose_name='Có lối đi giữa'),
        ),
        migrations.AddField(
            model_name='row',
            name='numbering_style',
            field=models.CharField(choices=[('left_to_right', 'Trái sang Phải (1,2,3,4...)'), ('center_out', 'Giữa ra Ngoài (lẻ trái, chẵn phải)'), ('right_to_left', 'Phải sang Trái'), ('vertical', 'Dọc (cho LG boxes)')], default='center_out', max_length=20, verbose_name='Kiểu đánh số ghế'),
        ),
    ]
