# Generated by Django 4.2 on 2025-10-06 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0005_alter_row_options_remove_row_name_row_aisle_width_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='display_number',
            field=models.CharField(blank=True, help_text='Số ghế hiển thị trên FE (có thể khác với number trong BE)', max_length=10, null=True, verbose_name='Số hiển thị'),
        ),
        migrations.AddField(
            model_name='seat',
            name='price_category',
            field=models.ForeignKey(blank=True, help_text='Để trống sẽ lấy từ hàng ghế', null=True, on_delete=django.db.models.deletion.SET_NULL, to='venues.pricecategory', verbose_name='Loại giá'),
        ),
        migrations.AddField(
            model_name='seat',
            name='spacing_after',
            field=models.IntegerField(default=0, help_text='Khoảng trống sau ghế này (không ẩn ghế)', verbose_name='Khoảng cách sau ghế (px)'),
        ),
        migrations.AlterField(
            model_name='pricecategory',
            name='name',
            field=models.TextField(verbose_name='Tên loại vé'),
        ),
    ]
