# Generated by Django 4.2 on 2025-10-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0006_seat_display_number_seat_price_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='seat_image',
            field=models.ImageField(blank=True, help_text='Ảnh chụp ghế thực tế để khách hàng xem', null=True, upload_to='seats/', verbose_name='Ảnh ghế thực tế'),
        ),
    ]
