# Generated by Django 4.2 on 2025-10-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0007_seat_seat_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='row',
            name='spacing_after',
            field=models.IntegerField(default=0, help_text='Khoảng trống sau hàng này (để tạo lối đi giữa các nhóm hàng)', verbose_name='Khoảng cách sau hàng (px)'),
        ),
    ]
