# Generated by Django 4.2 on 2025-10-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0008_row_spacing_after'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='rules',
            field=models.TextField(blank=True, help_text='Các quy định, lưu ý quan trọng cho khách hàng. Mỗi quy định nên viết trên 1 dòng.', verbose_name='Quy định và lưu ý'),
        ),
    ]
