# Generated by Django 4.2 on 2025-10-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0009_venue_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='logo_url',
            field=models.URLField(default='https://lh3.googleusercontent.com/pw/AP1GczOeY1ZKKsObbQ5Em5H14byD0GRz_-ydPBGZWzBOQbun4cB783CMb3NsYbucZAmrMlCE-YJ8r3Ll71Fthb-wyaMjuQbPTc1jAPLcf-3-NzjBqBuS_3NB2W6JzfAWZP3sRYBVzVxethfg4iJBam3EhoDp=w489-h301-s-no-gm', max_length=500, verbose_name='Logo URL'),
        ),
    ]
