# Generated by Django 5.2.7 on 2025-10-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0010_alter_contactinfo_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='row',
            name='orphan_seat_rule_enabled',
            field=models.BooleanField(default=True, help_text='Không cho đặt ghế nếu để lại 1 ghế trống ở giữa', verbose_name='Bật rule ghế mồ côi'),
        ),
    ]
