# Generated by Django 4.2 on 2025-10-14 09:10

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_booking_customer_address_booking_shipping_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Mã khách hàng sẽ nhập, ví dụ: 'SALE50', 'GIAM100K'", max_length=50, unique=True, verbose_name='Mã giảm giá')),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Giảm theo phần trăm'), ('FIXED_AMOUNT', 'Giảm số tiền cố định')], max_length=20, verbose_name='Loại giảm giá')),
                ('value', models.DecimalField(decimal_places=2, help_text='Nếu là phần trăm, nhập 50 cho 50%. Nếu là số tiền, nhập 100000 cho 100,000đ.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Giá trị')),
                ('max_usage', models.PositiveIntegerField(blank=True, help_text='Bỏ trống nếu không giới hạn.', null=True, verbose_name='Số lần sử dụng tối đa')),
                ('usage_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Số lần đã sử dụng thành công')),
                ('valid_from', models.DateTimeField(verbose_name='Hiệu lực từ ngày')),
                ('valid_to', models.DateTimeField(blank=True, help_text='Bỏ trống nếu không có ngày hết hạn.', null=True, verbose_name='Hiệu lực đến ngày')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('all_users', models.BooleanField(default=True, verbose_name='Áp dụng cho tất cả người dùng')),
                ('allowed_users', models.TextField(blank=True, help_text='Nhập email hoặc SĐT, mỗi giá trị cách nhau bởi dấu phẩy, không có khoảng trắng. Ví dụ: user1@gmail.com,0912345678,user2@gmail.com', verbose_name='Người dùng được phép')),
            ],
            options={
                'verbose_name': 'Mã giảm giá',
                'verbose_name_plural': 'Mã giảm giá',
                'ordering': ['-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='DiscountUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Đang chờ thanh toán'), ('COMPLETED', 'Đã hoàn thành'), ('CANCELLED', 'Đã hủy/Thất bại')], default='PENDING', max_length=20)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discount_usage', to='bookings.booking')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='discounts.discount')),
            ],
            options={
                'verbose_name': 'Lượt sử dụng giảm giá',
                'verbose_name_plural': 'Lượt sử dụng giảm giá',
            },
        ),
    ]
