# Generated by Django 4.2 on 2025-10-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='min_ticket_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Để trống nếu không yêu cầu số lượng tối thiểu', null=True, verbose_name='Số lượng vé tối thiểu'),
        ),
    ]
